# Generated by Django 3.1.3 on 2020-11-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120, verbose_name='问题描述')),
                ('date', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '问题库',
                'verbose_name_plural': '问题库',
                'db_table': 'dj_questions',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=120, verbose_name='问题')),
                ('votes', models.IntegerField(default=0, verbose_name='票数')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
            options={
                'verbose_name': '投票结果',
                'verbose_name_plural': '投票结果',
                'db_table': 'dj_choice',
            },
        ),
    ]
