"""empty message

Revision ID: a5b59f3d0bfc
Revises: 
Create Date: 2020-11-02 16:19:29.820762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5b59f3d0bfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test01')
    op.drop_table('student')
    op.drop_index('name', table_name='db_flask')
    op.drop_table('db_flask')
    op.drop_index('idx_name_birthday_phone_number', table_name='person_info')
    op.drop_table('person_info')
    op.drop_index('name', table_name='tbl_authors')
    op.drop_table('tbl_authors')
    op.drop_index('c4', table_name='index_demo')
    op.drop_table('index_demo')
    op.drop_table('hero')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('number'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('index_demo',
    sa.Column('c1', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('c2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('c3', mysql.CHAR(length=1), nullable=True),
    sa.Column('c4', mysql.VARCHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('c1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_index('c4', 'index_demo', ['c4'], unique=True)
    op.create_table('tbl_authors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'tbl_authors', ['name'], unique=True)
    op.create_table('person_info',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('birthday', sa.DATE(), nullable=False),
    sa.Column('phone_number', mysql.CHAR(length=11), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_name_birthday_phone_number', 'person_info', ['name', 'birthday', 'phone_number'], unique=False)
    op.create_table('db_flask',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'db_flask', ['name'], unique=True)
    op.create_table('student',
    sa.Column('number', mysql.INTEGER(), autoincrement=True, nullable=False, comment='学号'),
    sa.Column('name', mysql.VARCHAR(length=5), nullable=True, comment='姓名'),
    sa.PrimaryKeyConstraint('number'),
    comment='学生信息表',
    mysql_comment='学生信息表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('test01',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('context', mysql.VARCHAR(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
